replicaCount: 1

image:
  repository: edge
  tag: 1
  pullPolicy: Never

arguments:
  listenPort: 8080
  metricPort: 9100
  bootstrapServer: kafka-0.kafka.streaming.svc.cluster.local:9092
  topic: v1.raw

podAnnotations:
  "prometheus.io/scrape": "true"
  "prometheus.io/path": "/metrics"
  "prometheus.io/port": "9100"
