version: "2.2"

services:
  zookeeper:
    image: zookeeper:3.6.2
    environment:
      - ZOO_MY_ID=1
    volumes:
      - zkdata:/data
      - zklogs:/datalog

  kafka:
    image: wurstmeister/kafka:2.13-2.7.0
    restart: unless-stopped
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: EXT://:9092,INT://:9093
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INT:PLAINTEXT,EXT:PLAINTEXT
      KAFKA_ADVERTISED_LISTENERS: EXT://127.0.0.1:9092,INT://:9093
      KAFKA_INTER_BROKER_LISTENER_NAME: INT
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"
      KAFKA_CREATE_TOPICS: "v1.raw:3:1,v1.impressions:3:1,v1.user-agents:3:1,v1.dlq:3:1"
    volumes:
      - kafka:/kafka
    depends_on:
      - zookeeper

  pinot-controller:
    image: apachepinot/pinot:0.6.0-jdk11
    restart: unless-stopped
    volumes:
      - pinotcontroller:/tmp/data/controller
    ports:
      - "9000:9000"
    command: StartController -zkAddress zookeeper:2181
    depends_on:
      - kafka

  pinot-broker:
    image: apachepinot/pinot:0.6.0-jdk11
    restart: unless-stopped
    ports:
      - "8099:8099"
    command: StartBroker -zkAddress zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
      - pinot-controller

  pinot-server:
    image: apachepinot/pinot:0.6.0-jdk11
    restart: unless-stopped
    volumes:
      - pinotserver:/tmp/data/server
    ports:
      - "8098:8098"
    command: StartServer -zkAddress zookeeper:2181
    depends_on:
      - zookeeper
      - kafka
      - pinot-controller

volumes:
  zkdata:
  zklogs:
  kafka:
  pinotcontroller:
  pinotserver:
