apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "edge.fullname" . }}
  labels:
    {{- include "edge.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      {{- include "edge.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
      labels:
        {{- include "edge.selectorLabels" . | nindent 8 }}
    spec:
      containers:
        - name: {{ .Chart.Name }}
          image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
          imagePullPolicy: {{ .Values.image.pullPolicy }}
          args:
            - "-listen=0.0.0.0:{{ .Values.arguments.listenPort }}"
            - "-metric-listen=0.0.0.0:{{ .Values.arguments.metricPort }}"
            - "-bootstrap-server={{ .Values.arguments.bootstrapServer }}"
            - "-topic={{ .Values.arguments.topic }}"
            - "-stdout=false"
          ports:
            - name: http
              containerPort: {{ .Values.arguments.listenPort }}

            - name: metrics
              containerPort: {{ .Values.arguments.metricPort }}

          readinessProbe:
            httpGet:
              path: /-/ready
              port: http
          livenessProbe:
            httpGet:
              path: /-/ready
              port: http
