apiVersion: v1
kind: Service
metadata:
  name: {{ include "edge.fullname" . }}
  labels:
    {{- include "edge.labels" . | nindent 4 }}
spec:
  type: "ClusterIP"
  ports:
    - port: {{ .Values.arguments.listenPort }}
      name: http
      targetPort: http

  selector:
    {{- include "edge.selectorLabels" . | nindent 4 }}
