#!/bin/bash
set -e

# druid database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${DRUID_USER} WITH PASSWORD '${DRUID_PASSWORD}';
    CREATE DATABASE ${DRUID_DATABASE};
    GRANT ALL PRIVILEGES ON DATABASE ${DRUID_DATABASE} TO ${DRUID_USER};
EOSQL

# redash database
psql -v ON_ERROR_STOP=1 --username "$POSTGRES_USER" --dbname "$POSTGRES_DB" <<-EOSQL
    CREATE USER ${REDASH_USER} WITH PASSWORD '${REDASH_PASSWORD}';
    CREATE DATABASE ${REDASH_DATABASE};
    GRANT ALL PRIVILEGES ON DATABASE ${REDASH_DATABASE} TO ${REDASH_USER};
EOSQL
